name: push
description: combine multi-arch image and push
inputs:
  version:
    description: version
    required: true
  latest:
    description: if tag latest
    required: false
  latest_major:
    description: if tag latest major version
    required: false
  dev:
    description: if set then it's a dev version
  dev_macos:
    description: if set then it's a dev macos version
runs:
  using: "composite"
  steps:
    - name: Build image
      env:
        PHP_VER: ${{ inputs.version }}
        PHP_DEV: ${{ inputs.dev }}
        PHP_DEV_MACOS: ${{ inputs.dev_macos }}
        LATEST: ${{ inputs.latest }}
        LATEST_MAJOR: ${{ inputs.latest_major }}
      run: |
        . $GITHUB_ACTION_PATH/release.sh
      shell: bash
      working-directory: ${{ inputs.workdir }}
